---
- name: IOS STATUS
  hosts: CSR1kv
  gather_facts: false
  connection: local

  tasks:
    - name: run show version on remote devices
      ios_command:
        commands:
          - show version
    
    - name: run show version on remote devices
      ios_command:
        commands:
          - show ip int brief

    - name: run show version and check to see if output contains IOS
      ios_command:
        commands:
          - show version
        wait_for: result[0] contains IOS

    - name: run multiple commands on remote nodes
      ios_command:
        commands:
          - show version
          - show interfaces
      register: config

    - name: run multiple commands and evaluate the output
      ios_command:
        commands:
          - show version
          - show interfaces
        wait_for:
          - result[0] contains IOS
          - result[1] contains GigabitEthernet1 #Endret fra Loopback0, siden det ikke eksisterer

    - name: run commands that require answering a prompt
      ios_command:
        commands:
          - command: 'clear counters GigabitEthernet1'
            prompt: 'Clear "show interface" counters on this interface \[confirm\]'
            answer: 'y'
            
